# Generated by Django 4.0.6 on 2024-01-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_valuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('description', models.TextField()),
                ('child_sku', models.TextField()),
                ('child_sku_description', models.TextField()),
                ('mech_per_pcs', models.IntegerField()),
            ],
        ),
    ]
