# Generated by Django 4.0.6 on 2024-01-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='dashboard.product'),
        ),
    ]
