# Generated by Django 4.0.6 on 2024-01-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_promo_related_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='child_sku_description',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='description',
        ),
    ]
