# Generated by Django 4.0.6 on 2023-11-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
