# Generated by Django 4.0.6 on 2023-11-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default='static/gallery/selfie.jpg', upload_to='gallery/'),
        ),
    ]
